### ISSUE TITLE
Dependency Currency Conflict with Telemetry

### ISSUE THREAD

**Issue by cdesch** [ludwikbukowski/telemetry_influxdb#28]
Is there anything holding `telemetry_influxdb` back from updating the [`telemetry`](https://github.com/beam-telemetry/telemetry) dependency to `1.0.0`?

```
➜  ex_def git:(main) ✗ mix deps.get
Resolving Hex dependencies...

Failed to use "telemetry" (version 1.0.0) because
  broadway (version 1.0.1) requires ~> 0.4.3 or ~> 1.0
  broadway_rabbitmq (version 0.7.1) requires ~> 0.4.3 or ~> 1.0
  ecto_sql (version 3.7.1) requires ~> 0.4.0 or ~> 1.0
  ex_aws (version 2.2.8) requires ~> 0.4.3 or ~> 1.0
  horde (version 0.8.5) requires ~> 1.0.0 or ~> 0.4.0
  telemetry_influxdb (version 0.2.0) requires ~> 0.4.0
  mix.lock specifies 1.0.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

**Comment by cdesch** [comment]
I'm trying to run the tests to see if things work out. Here are the failing tests with no changes other than updating the docker images for InfluxDb in the [makefile]( https://github.com/cdesch/telemetry_influxdb/blob/cd59cd98b102ab298bd57fea6d343c6831a48bfa/Makefile)


```
  1) test Events reported -  only specified events are reported for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:238
     ** (Eventually) function returned false
     code: clear_series(context, "event.one")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:258: (test)

.

  2) test Events reported -  event is reported with correct data types for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:207
     ** (Eventually) function returned false
     code: clear_series(context, "calls.failed")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:232: (test)



  3) test Events reported -  events are reported with global pre-defined tags for v1 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:266
     ** (EXIT from #PID<0.1078.0>) shutdown: failed to start child: :default_WorkerPool
         ** (EXIT) already started: #PID<0.1070.0>

..

  4) test Events reported -  event is reported when specified by its name for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:187
     ** (Eventually) function returned false
     code: clear_series(context, "requests.failed")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:201: (test)



  5) test Events reported -  events are reported from two independent reporters for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:424
     ** (Eventually) function returned false
     code: clear_series(context, "servers1.down")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:464: (test)

....

  6) test Events reported -  events are reported with global pre-defined tags for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:266
     ** (Eventually) function returned false
     code: clear_series(context, "memory.leak")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:289: (test)



  7) test Events reported -  event is reported with correct data types for v1 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:207
     ** (EXIT from #PID<0.1154.0>) shutdown: failed to start child: :default_WorkerPool
         ** (EXIT) already started: #PID<0.1146.0>

..

  8) test Events reported -  events are reported with event-specific tags for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:295
     ** (Eventually) function returned false
     code: clear_series(context, "system.crash")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:311: (test)

..

  9) test Events reported -  events are reported with metadata tags specified for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:317
     ** (Eventually) function returned false
     code: clear_series(context, "database.repo")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:333: (test)

.....

 10) test Events reported -  events are reported with special characters for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:339
     ** (Eventually) function returned false
     code: clear_series(context, "event.special1")
     stacktrace:
       (eventually 0.1.0) lib/eventually.ex:12: Eventually.eventually/5
       (eventually 0.1.0) lib/eventually.ex:25: Eventually.eventually/5
       test/telemetry_influx_db_test.exs:362: (test)



 11) test Events reported -  events are detached after stopping reporter for v2 http API (TelemetryInfluxDBTest)
     test/telemetry_influx_db_test.exs:369
     ** (EXIT from #PID<0.1243.0>) shutdown: failed to start child: :default_WorkerPool
         ** (EXIT) already started: #PID<0.1235.0>

......

Finished in 43.4 seconds (0.2s async, 43.1s sync)
52 tests, 11 failures

Randomized with seed 584735
make: *** [test] Error 2

```
